<h2>Tokens

In [1]:
text = "Hello Iam Gagan from Mangalore"
tokens_split = text.split()
print("Split Tokenization:", tokens_split)

Split Tokenization: ['Hello', 'Iam', 'Gagan', 'from', 'Mangalore']


In [2]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to C:\Users\Gagan K
[nltk_data]     M\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Gagan K
[nltk_data]     M\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [3]:
from nltk.tokenize import word_tokenize
tokens_nltk = word_tokenize(text)
print("NLTK Tokenization:", tokens_nltk)

NLTK Tokenization: ['Hello', 'Iam', 'Gagan', 'from', 'Mangalore']


In [4]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp(text)
tokens_spacy = [token.text for token in doc]
print("spaCy Tokenization:", tokens_spacy)

spaCy Tokenization: ['Hello', 'Iam', 'Gagan', 'from', 'Mangalore']


In [5]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
tokens_hf = tokenizer.tokenize(text)
print("Hugging Face Tokenization:", tokens_hf)

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.


Hugging Face Tokenization: ['hello', 'ia', '##m', 'gaga', '##n', 'from', 'manga', '##lore']


<h2> Stemming

In [6]:
from nltk.stem.snowball import SnowballStemmer
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')

stemmer = SnowballStemmer("english", True)
text = "There is nothing either good or bad but thinking makes it so."
words = word_tokenize(text)
stemmed_words = [stemmer.stem(word) for word in words]
print("Stemmed:", stemmed_words)

Stemmed: ['there', 'is', 'noth', 'either', 'good', 'or', 'bad', 'but', 'think', 'make', 'it', 'so', '.']


[nltk_data] Downloading package stopwords to C:\Users\Gagan K
[nltk_data]     M\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


<h2> Lemmatization

In [7]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('wordnet')

text = "The leaves are falling from the trees."
words = word_tokenize(text)
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
print("Lemmatized words:", lemmatized_words)

[nltk_data] Downloading package punkt to C:\Users\Gagan K
[nltk_data]     M\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Gagan K
[nltk_data]     M\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Lemmatized words: ['The', 'leaf', 'are', 'falling', 'from', 'the', 'tree', '.']


<h2> Embeddings

In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
corpus = ['dog', 'cat', 'dog', 'fish']
corpus = np.array(corpus).reshape(-1, 1)
onehot_encoder = OneHotEncoder()
onehot_encoded = onehot_encoder.fit_transform(corpus)
print(onehot_encoded)

  (0, 1)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 2)	1.0


In [9]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
